name: abc
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - run: cd ${{ github.workspace }}
    - run: ls -la
    - run: pwd
    - run: npx embedme README.md
